### ISSUE TITLE
do exit 0 for `Cannot execute the 'am' shell command`

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/appium#325] opened 2024-01-08 20:15 UTC
```
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Cannot execute the 'am' shell command. Original error: Command '/opt/android/platform-tools/adb -P 5037 -s G..4BD shell am broadcast -n com.../.AdbInteractionBroadcastReceiver -a com....CHECK_ENVIRONMENT --es targetPackage com.d.d..' timed out after 20000ms. StdOut: Broadcasting: Intent { act=com.d.CHECK_ENVIRONMENT flg=0x400000 cmp=com.../.AdbInteractionBroadcastReceiver (has extras) }
. StdErr: [[[--udid G..BD --name Amazon_FireTV_Stick_Lite --sessionId db600880-d561-4f20-a470-b3090147314a]]]
Build info: version: '4.7.0', revision: '0a5b49d16f'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.201-191.748.amzn2.x86_64', java.version: '17.0.8'
Driver info: io.appium.java_client.android.AndroidDriver
...
Session ID: db600880-d561-4f20-a470-b3090147314a
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:53)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:184)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:262)
	at com.zebrunner.carina.webdriver.listener.EventFiringAppiumCommandExecutor.execute(EventFiringAppiumCommandExecutor.java:79)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:541)
	at org.openqa.selenium.remote.RemoteWebDriver.executeScript$original$ldy30G87(RemoteWebDriver.java:478)
	at org.openqa.selenium.remote.RemoteWebDriver.executeScript$original$ldy30G87$accessor$lGs1cOJ5(RemoteWebDriver.java)
	at org.openqa.selenium.remote.RemoteWebDriver$auxiliary$wHjq7JEN.call(Unknown Source)
	at com.zebrunner.agent.core.webdriver.PublicMethodInvocationInterceptor.onPublicMethodInvocation(PublicMethodInvocationInterceptor.java:18)
	at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.openqa.selenium.support.decorators.WebDriverDecorator.call(WebDriverDecorator.java:247)
	at org.openqa.selenium.support.decorators.DefaultDecorated.call(DefaultDecorated.java:48)
	at org.openqa.selenium.support.decorators.WebDriverDecorator.lambda$createProxy$0(WebDriverDecorator.java:309)
	at net.bytebuddy.renamed.java.lang.Object$ByteBuddy$TZ4fkILn.executeScript(Unknown Source)
	at com.zebrunner.carina.utils.android.IAndroidUtils.executeShell(IAndroidUtils.java:852)
	at com.zebrunner.carina.utils.android.IAndroidUtils.executeShell(IAndroidUtils.java:822)
...
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:361)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:296)
	at org.testng.internal.invokers.TestInvoker.runConfigMethods(TestInvoker.java:823)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:590)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by vavadikb** [comment] 2024-02-27 13:13
ticket resolved in pull request 
https://github.com/zebrunner/appium/pull/336

**Closed by vavadikb** 2024-02-27 13:13 UTC
Labels: enhancement

**Comment by dhreben** [comment] 2024-03-04 13:36
Can't reproduce.Will be tested on prod
