### ISSUE TITLE
do exit 1 for `Cannot find any free port in range`

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/appium#315] opened 2023-12-01 13:44 UTC
capture error and do appium container restart

```
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: An unknown server-side error occurred while processing the command. Original error: Cannot find any free port in range 8200..8299}. Please set the available port number by providing the systemPort capability or double check the processes that are locking ports within this range and terminate these which are not needed anymore[[[--udid B...6 --name Nokia_7_Plus --sessionId eeb7e3d3-fcdb-4cc0-82f0-3c56af08c972]]] Host info: host: '6c0f5ee2f5e2', ip: '172.18.0.31' Build info: version: '4.7.0', revision: '0a5b49d16f' System info: os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-142-generic', java.version: '17.0.9' Driver info: io.appium.java_client.android.AndroidDriver Command: [null, newSession 
```

**Comment by vavadikb** [comment] 2024-02-27 13:12
ticket resolved in pull request https://github.com/zebrunner/appium/pull/342 

this error is related to appium ports, it appears when trying to create a session, but appium cannot find a free port for this

**Closed by vavadikb** 2024-02-27 13:12 UTC
Labels: enhancement

**Comment by vavadikb** [comment] 2024-02-27 13:15
needs testing

**Comment by vavadikb** [comment] 2024-02-27 13:19
tried to reproduce this error, when all ports got busy on test server, we received an error not related to the start of the session

**Comment by dhreben** [comment] 2024-03-04 13:40
Can't reproduce.Will be tested on prod
