### ISSUE TITLE
Error: `Couldn't initialize inotify.` 

### ISSUE THREAD

**Issue by azarouski** [zebrunner/appium#417] opened 2024-08-15 11:22 UTC
`public.ecr.aws/zebrunner/appium:2.1`
```text
Couldn't initialize inotify.  Are you running Linux 2.6.13 or later, and was the
CONFIG_INOTIFY option enabled when your kernel was compiled?  If so,
something mysterious has gone wrong.  Please e-mail radu.voicilas@gmail.com
and mention that you saw this message.
```

**Comment by vdelendik** [comment] 2024-08-15 17:48
that's not a bug but Linux configuration step which was added to the mcloud-agent steps: https://github.com/zebrunner/mcloud-agent#linux-os
```
[Optional] Increased fs.inotify.max_user_instances to workaround https://github.com/zebrunner/mcloud-agent/issues/328
sudo sysctl fs.inotify.max_user_instances=2048
```

closing as won't fix

**Closed by vdelendik** 2024-08-15 17:48 UTC
Labels: bug
