### ISSUE TITLE
do process.exit(0) from appium when `socket hang up` occur

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/appium#116] opened 2022-05-06 12:41 UTC
```
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up[[[--udid 000...2E --name iPad_8_Gen -...
content_copy
expand_less
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up[[[--udid 000...2E --name iPad_8_Gen --sessionId ac4850c3-7553-4e93-89af-f079cd5d8a51]]]
```

**Comment by vdelendik** [comment] 2023-07-18 17:21
move to 2.1 to keep an eye on how appium 2.0 works

**Comment by vavadikb** [comment] 2024-02-27 13:12
ticket resolved in pull request 
https://github.com/zebrunner/appium/pull/339

need test

**Closed by vavadikb** 2024-02-27 13:12 UTC
Labels: enhancement

**Comment by dhreben** [comment] 2024-03-04 13:43
Can't reproduce.Will be tested on prod
