### ISSUE TITLE
 Error: [Appium] Received SIGTERM - shutting down.

### ISSUE THREAD

**Issue by dhreben** [zebrunner/appium#55] opened 2022-02-09 10:49 UTC
Sometimes Appium shows an error `[Appium] Received SIGTERM - shutting down`, and then does not find an active session.
After that, the WDA application is installed and launched on the device.
The SIGTERM upload method is registered on the device and it starts working as before.
All this happens within 8-10 seconds.

The status in containers also changes.
`docker ps -a `

<img width="360" alt="Screenshot 2022-02-09 at 13 32 30" src="https://user-images.githubusercontent.com/50950954/153182842-8cf412b0-ed0f-4bfb-a17e-fd224e2ba207.png">

Appium v1.22.2

```

2022-02-09 09:36:27:085 - [Appium] Received SIGTERM - shutting down
2022-02-09 09:36:27:085 - [debug] [Appium] There are no active sessions for cleanup
Exit status: 0
---------------------------------------------------------
processes BEFORE EXIT:
UID          PID    PPID  C STIME TTY          TIME CMD
root           1       0  0 Feb08 pts/0    00:00:00 /bin/bash /root/entry_point.
root          79       1  0 Feb08 pts/0    00:00:00 ios runwda --bundleid=com.fa
root         181       1  0 Feb08 pts/0    00:00:00 [Xvfb]
root       21651       1  0 01:36 pts/0    00:00:00 ps -ef
---------------------------------------------------------
{"deviceList":["0000...01E","00........402E","00............402E","000......03A","000...........801E","0000......801E","000......02E","000.....001E","00........F9402E","000.......02E"]}
DEVICE_UDID: 000............402E
[09/02/2022 01:36:27] Pair device 00.............02E
{"level":"info","msg":"Successfully paired 00...........402E","time":"2022-02-09T01:36:27-08:00"}
[09/02/2022 01:36:27] populating device info
[09/02/2022 01:36:28] Mount /opt/zebrunner/DeveloperDiskImages/14.6/DeveloperDiskImage.dmg
{"level":"warning","msg":"there is already a developer image mounted, reboot the device if you want to remove it. aborting.","time":"2022-02-09T01:36:28-08:00"}
{"image":"/opt/zebrunner/DeveloperDiskImages/14.6/DeveloperDiskImage.dmg","level":"info","msg":"success mounting image","time":"2022-02-09T01:36:28-08:00","udid":"00....................02E"}
[09/02/2022 01:36:28] Installing WDA application on device
{"appPath":"/opt/WebDriverAgent.ipa","device":"0000.................02E","level":"info","msg":"installing","time":"2022-02-09T01:36:28-08:00"}
{"level":"info","msg":"installing","percentComplete":5,"status":"CreatingStagingDirectory","time":"2022-02-09T01:36:29-08:00"}
{"level":"info","msg":"installing","percentComplete":15,"status":"ExtractingPackage","time":"2022-02-09T01:36:29-08:00"}
{"level":"info","msg":"installing","percentComplete":20,"status":"InspectingPackage","time":"2022-02-09T01:36:29-08:00"}
{"level":"info","msg":"installing","percentComplete":20,"status":"TakingInstallLock","time":"2022-02-09T01:36:29-08:00"}
{"level":"info","msg":"installing","percentComplete":30,"status":"PreflightingApplication","time":"2022-02-09T01:36:29-08:00"}
{"level":"info","msg":"installing","percentComplete":30,"status":"InstallingEmbeddedProfile","time":"2022-02-09T01:36:29-08:00"}
{"level":"info","msg":"installing","percentComplete":40,"status":"VerifyingApplication","time":"2022-02-09T01:36:29-08:00"}
{"level":"info","msg":"installing","percentComplete":50,"status":"CreatingContainer","time":"2022-02-09T01:36:29-08:00"}
{"level":"info","msg":"installing","percentComplete":60,"status":"InstallingApplication","time":"2022-02-09T01:36:29-08:00"}
{"level":"info","msg":"installing","percentComplete":70,"status":"PostflightingApplication","time":"2022-02-09T01:36:29-08:00"}
{"level":"info","msg":"installing","percentComplete":80,"status":"SandboxingApplication","time":"2022-02-09T01:36:29-08:00"}
{"level":"info","msg":"installing","percentComplete":90,"status":"GeneratingApplicationMap","time":"2022-02-09T01:36:29-08:00"}
{"level":"info","msg":"installation successful","time":"2022-02-09T01:36:30-08:00"}
[09/02/2022 01:36:30] Starting WebDriverAgent application on port 8100
detecting WDA_HOST ip address...
attempt 1
attempt 2
attempt 3
attempt 4
attempt 5
Detected WDA_HOST ip: 192.168.88.238
WDA_PORT=8100
[09/02/2022 01:36:35] Starting WebDriverAgent 1st session
bundleId: com.apple.springboard
sessionId: 6DD....................A44
[09/02/2022 01:36:35] Stopping 1st default WebDriverAgent session
sessionId: 6DD495F6-8..............DD4A44

```

**Comment by vdelendik** [comment] 2022-02-09 12:20
@dhreben we have to review healthcheck logs to determine the reason. auto-healing is great and I suspect WDA is not reponding but better to confirm:
```
docker inspect --format "{{json .State.Health }}" <container-name>-appium | jq
```

**Comment by vdelendik** [comment] 2022-02-14 21:40
closing as can't reproduce

**Closed by vdelendik** 2022-02-14 21:40 UTC
Labels: bug
